name: Sync luci from coolsnowwolf/lede

on:
  workflow_dispatch:
  #schedule:
    #- cron: "0 0 * * 0" # 每周日午夜触发

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Sync luci
        run: |
          git clone --depth=1 https://github.com/linkease/nas-packages.git tmp
          cp -r tmp/package/luci ./
          cp -r luci $GITHUB_WORKSPACE/luci

        working-directory: ${{ github.workspace }}
      - name: Commit changes
        uses: EndBug/add-and-commit@v7
        with:
          author_name: Your Name
          author_email: your-email@example.com
          message: "Sync luci from coolsnowwolf/lede"
          add: "."
