name: Sync Packages

on:
  push:
    branches:
      - main  # 修改为您要同步的分支
  workflow_dispatch:

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Clone nas-packages
      run: git clone --depth=1 https://github.com/linkease/nas-packages.git tmp

    - name: Copy packages
      run: cp -r tmp/* $GITHUB_WORKSPACE/luci/

    - name: Commit and push changes
      uses: EndBug/add-and-commit@v7
      with:
        message: Sync nas-packages at ${{ github.sha }}
        add: .
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
